[project]
due_date = "2025-04-08 23:59:59 -0700"
build = "go"
timeout = 7200

[[tests]]
name = "TestPhil"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestPHIL"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestBio"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestGuitar"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestMultiple"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

