[project]
due_date = "2025-02-10 23:59:59 -0800"
build = "go"

[[tests]]
name = "TestExtract"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestCleanHref"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestDownload"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 40

[[tests]]
name = "TestCrawl"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 40
