[project]
due_date = "2025-03-04 23:59:59 -0800"
build = "go"

[[tests]]
name = "TestExtract"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 5

[[tests]]
name = "TestCleanHref"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 5

[[tests]]
name = "TestDownload"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 5

[[tests]]
name = "TestCrawl"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 5

[[tests]]
name = "TestStop"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 15

[[tests]]
name = "TestTfIdf"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 40
